### ISSUE TITLE
Feature Request: Ability to create folders recursively 

### ISSUE THREAD

**Issue by mhanuszh** [igorskyflyer/vscode-new-folder#1]

**Comment by igorskyflyer** [comment]
Yes, it's on my To-Do list since I started creating the extension but it is not possible with "native" VS Code dialogs but as soon as I finish implementing a custom Folder Pick dialog, it will be. 😄

Stay tuned. 🙌😁

**Comment by igorskyflyer** [comment]
@mhanuszh, done! 🥳
