### ISSUE TITLE
Add folder to workspace instead of opening it directly

### ISSUE THREAD

**Issue by wmstack** [igorskyflyer/vscode-new-folder#31]
Hello, it would be nice if there was an option to add the folder to workspace instead of opening it and closing the current workspace. I like to use an embedded file picker so this extension is pretty great. Also have a command to programmatically pick the starting location via an argument to the vscode command.

Cheers!

**Comment by igorskyflyer** [comment]
Hello, thank you for your suggestions, they both seem valid. It was intended for the extension to only create new folders - hence the name - and then open the newly created workspace but I will take into account your suggestion and prepare both features for the next release. 😁

Cheers, mate! 🤙🏼

**Comment by igorskyflyer** [comment]
The ETA of the next release should be at the end of the following week. 😁

**Comment by igorskyflyer** [comment]
I will be opening a separate issue for the second part of your comment about the command line arguments, during the following week. 😀

Please consider leaving a 5⭐ review on the Marketplace for my extension, it means a lot, thanks. 🤩

**Comment by igorskyflyer** [comment]
> Hello, it would be nice if there was an option to add the folder to workspace instead of opening it and closing the current workspace. I like to use an embedded file picker so this extension is pretty great. Also have a command to programmatically pick the starting location via an argument to the vscode command.
> 
> Cheers!

I've brainstormed a few ideas for how to solve the arguments passing in order to set the starting location for the folder creation but now that I think about it, I don't think it is even necessary because you issue the `"vscode"` command along with the directory path and then when VS Code starts up you can use the new `"New Folder in Project"` command I added, as you also suggested.

Does that match your workflow or you have a different use case?

**Comment by wmstack** [comment]
Hmm there is a problem with the current version. When a folder is created, it isn't added to the current workspace, it is just created and doesn't appear in the list of workspaces? Another problem is that "create in project" is only able to create new folders, but is not able to pick an already-existing directory, which the older command is able to do.

I didn't think there would be technical difficulty for setting the starting location. I don't mean to create a new quick-pick for the starting location. What I meant by have a command to programmaticaly pick the starting location was nothing more than the command supplied in the `keybindings.json`, not via a quick-pick. For example, if I always wanted to start from the home directory, I would put the `args: "C:\Users\<me>\"` and that would be picked up by the closure passed to `vscode.commands.registerCommand`.

Do what is easiest, as I find a lot of it supefluous anyway. The point is not to reach for the command line. For example to me, adding a folder to the workspace involves nothing more than `zi; code -a .` and the `zi` (zoxide interactive) would walk me through finding my directory from the home directory.
