### ISSUE TITLE
Feature Request: Option to disable emojis

### ISSUE THREAD

**Issue by mhanuszh** [igorskyflyer/vscode-new-folder#5]
Thank you for your work in the 2.0 release!

In 2.0 the folders and actions are accompanied by colorful emojis, this is a nice feature, but it deviates from the standard vscode experience (as of no eye candy).

Could you please give us an option to disable them?

**Comment by igorskyflyer** [comment]
Actually, it already is available, just not publicly exposed, emojis and Codicons are available. 😆

As mentioned, the extension's core - [FolderPicker](https://github.com/igorskyflyer/npm-vscode-folderpicker) is still work in progress and it *will* go through a lot of changes, that being one of them.

I have a few more tweaks for it, I'll push the changes today which will be reflected in the extension as well. 😄

Thanks for the feedback and happy coding! 🥳

**Comment by igorskyflyer** [comment]
I have postponed the release - even more features are coming. 🥳🎉
Should be released by tomorrow. ☺

**Comment by igorskyflyer** [comment]
New version has been released and it includes this feature  and many more, including major performance improvements, I recommend updating the extension. Happy coding! 🎉
